Nd add ajax
SaraDawner2000/photogram-ajax pull request #1
Opened 2024-07-09 20:59 UTC by SaraDawner2000

Ajaxify photogram

2024-07-10 14:40 UTC, YoungSong99 requested changes
Could you update the follow_request id to class? Please refer to the comment in app/views/follow_requests/_form.html.erb. :)

2024-07-10 14:40 UTC, YoungSong99 commented on Gemfile
> +
Great idea to use the Robocop gem for assistance with formatting!

2024-07-10 14:40 UTC, YoungSong99 commented on app/views/comments/_form.html.erb
>      <% if comment.errors.any? %>
Id looks clean!

2024-07-10 14:40 UTC, YoungSong99 commented on app/views/comments/destroy.js.erb
> +  $(this).remove();
using 'this' is cleaver!

2024-07-10 14:40 UTC, YoungSong99 commented on app/views/follow_requests/_form.html.erb
> +<%= form_with(model: follow_request, class: "d-inline-block", local: false, id: "#{dom_id(current_user)}_follow_request_form") do |form| %>
I recommend using 'class' instead of 'id' for modifying other buttons. Additionally, it would be better to include dom_id(@following_request.sender) and dom_id(@following_request.recipient) for more targeted class names.

2024-07-10 15:34 UTC, SaraDawner2000 commented on app/views/follow_requests/_form.html.erb
> +<%= form_with(model: follow_request, class: "d-inline-block", local: false, id: "#{dom_id(current_user)}_follow_request_form") do |form| %>
Thank you! Fixed now

2024-07-10 20:22 UTC, ahuynh3a approved these changes
Great job Natalie! Your code is good and your application works!

2024-07-10 20:22 UTC, ahuynh3a commented on app/controllers/comments_controller.rb
> +        format.js
Great job for being mindful of white spaces!

2024-07-10 20:22 UTC, ahuynh3a commented on app/views/comments/_comment.html.erb
> +        <%= link_to comment,
nitpik: remove unnecessary white spaces

2024-07-10 20:22 UTC, ahuynh3a commented on app/views/comments/_form.html.erb
> +  <%= form_with(model: comment, local: false) do |form| %>
great job being mindful of when to use local:false and remote:true

2024-07-10 20:22 UTC, ahuynh3a commented on app/views/comments/update.js.erb
> +$("#<%= dom_id(@comment.photo) %>_<%= dom_id(@comment) %>_form").replaceWith("<%= j(render @comment) %>");
This is great! consider using variables to make your code more legible!

2024-07-10 20:22 UTC, ahuynh3a commented on app/views/follow_requests/create.js.erb
> +var follow_button = $(".<%= dom_id(current_user) %>_follow_request_to_<%=dom_id(@follow_request.recipient) %>_form");
great job!

2024-07-10 20:25 UTC, ahuynh3a commented on app/views/follow_requests/_form.html.erb
> +<%= form_with(model: follow_request, class: "d-inline-block", local: false, id: "#{dom_id(current_user)}_follow_request_form") do |form| %>
You actually do not need an id here because you are not using it in your js.erb files!

2024-07-11 13:55 UTC, YoungSong99 approved these changes
Thanks for the update! Looks great 👍

2024-07-15 20:23 UTC, merged